# Name of workflow
name: wake up apps

# When to run this workflow - 'push': runs whenever code is pushed/committed to this repo
# 'workflow_dispatch': Manually through GitHub UI button
# 'schedule': as per some schedule (time based)

on: workflow_dispatch

# If you want to take input change code
# on:
#   workflow_dispatch:
#     inputs:
#       urls:
#         description: 'List of websites to keep active'
#         required: true
#         default: '[]'

# urls is name of variable
# If type not mentioned takes it as string default
# type: string, boolean, number, choice (can choose from dropdown)

# Create a job called run-script, and make sure it runs on latest ubuntu
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    # gets python code from repo
    - uses: actions/checkout@v2
    # sets up python environment
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    # Each step can have name - not compulsory
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Install Google Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    # Runs python code
    - name: Run Python code
      run: python script.py

# If you want to pass input to python code as commandline argument
# run: python script.py '${{ github.event.inputs.urls }}'
