# Name of workflow
name: wake up apps

# When to run this workflow - 'push': runs whenever code is pushed/committed to this repo
# 'workflow_dispatch': Manually through GitHub UI button
# 'schedule': as per some schedule
on: workflow_dispatch

# Create a job called run-script, and make sure it runs on latest ubuntu
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    # gets python code from repo
    - uses: actions/checkout@v2
    # sets up python environment
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    # Each step can have name - not compulsory
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Install Google Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    # Runs code
    - run: python script.py
